version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      default-days: 7
      exclude:
        - "typescript"
        - "govuk-frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ministryofjustice/hmpps-github-actions/*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "helm"
    cooldown:
      default-days: 7
    directory: "/helm_deploy/hmpps-developer-portal"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: "docker"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
