---
generic-service:
  nameOverride: hmpps-developer-portal
  productId: 'DPS000'

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-developer-portal
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-developer-portal-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_TLS_ENABLED: 'true'
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/'
    ALERTMANAGER_URL: "http://monitoring-alerts-service.cloud-platform-monitoring-alerts:8080/alertmanager"
    SERVICE_CATALOGUE_TIMEOUT_RESPONSE: 50000
    SERVICE_CATALOGUE_TIMEOUT_DEADLINE: 50000

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-developer-portal:
      APPINSIGHTS_INSTRUMENTATIONKEY: 'APPINSIGHTS_INSTRUMENTATIONKEY'
      SESSION_SECRET: 'SESSION_SECRET'
      SERVICE_CATALOGUE_TOKEN: 'SERVICE_CATALOGUE_TOKEN'

  allowlist:
    groups:
      - internal
      - prisons
      - unilink_staff

generic-prometheus-alerts:
  targetApplication: hmpps-developer-portal
