---
# Per environment values which override defaults in hmpps-developer-portal/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-developer-portal-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-developer-portal-dev.hmpps.service.justice.gov.uk"
    STRAPI_PRODUCTS_URL: "https://service-catalogue.hmpps.service.justice.gov.uk/v1"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
