---
# Per environment values which override defaults in hmpps-developer-portal/values.yaml

generic-service:
  ingress:
    host: developer-portal.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://developer-portal.hmpps.service.justice.gov.uk"
    SERVICE_CATALOGUE_URL: "https://service-catalogue.hmpps.service.justice.gov.uk"

  namespace_secrets:
    elasticache-redis-dev:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service
