---
# Per environment values which override defaults in hmpps-developer-portal/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: developer-portal-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://developer-portal-dev.hmpps.service.justice.gov.uk"
    SERVICE_CATALOGUE_URL: "https://service-catalogue.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
