---
# Per environment values which override defaults in hmpps-developer-portal/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: developer-portal-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://developer-portal-dev.hmpps.service.justice.gov.uk"
    SERVICE_CATALOGUE_URL: "https://service-catalogue.hmpps.service.justice.gov.uk"

  namespace_secrets:
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

  # Set the alert for Elasticache's Engine CPU threshold value between 0 and 1.
  elastiCacheAlertsEngineCPUThreshold: 0.30
  elastiCacheAlertsEngineCPUThresholdMinutes: 5

  # Set the alert for Elasticache's CPU threshold - value between 0 and 100.
  elastiCacheAlertsCPUThreshold: 9
  elastiCacheAlertsCPUThresholdMinutes: 5

  # Set the alert for Elasticache's FreeMemory threshold - value should be above 150MB.
  elastiCacheAlertsFreeMemoryThreshold: 150
  elastiCacheAlertsFreeMemoryThresholdMinutes: 5
