---
# Per environment values which override defaults in hmpps-developer-portal/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: developer-portal-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://developer-portal-dev.hmpps.service.justice.gov.uk"
    SERVICE_CATALOGUE_URL: "https://service-catalogue-dev.hmpps.service.justice.gov.uk"
    NODE_ENV: "development"
    RECOMMENDED_VERSIONS_TTL_MS: "21600000"
    HMPPS_TEMPLATE_COMPONENT_NAME: "hmpps-template-kotlin"
    RECOMMENDED_VERSIONS_KOTLIN_ONLY: "true"

  namespace_secrets:
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod
