---
# Per environment values which override defaults in hmpps-developer-portal/values.yaml

generic-service:
  ingress:
    host: hmpps-developer-portal.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-developer-portal.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service
