name: Integration tests
on:
  workflow_call:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"
permissions:
  contents: read
jobs:
  integration_test:
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    steps:
      - uses: actions/checkout@v4
      # Using self-hosterd runners means that we can't run the redis service via docker
      - name: Install Redis
        run: sudo apt update && sudo apt install -y redis-server
      - name: Start Redis server
        run: sudo service redis-server start
      - name: Wait for Redis to be ready
        run: |
          until nc -zv localhost 6379; do
            echo "Waiting for Redis...";
            sleep 1;
          done
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm_build_artifacts
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm_build_artifacts
          path: |
            build/
            dist/
            assets/stylesheets/
      - name: Get wiremock
        shell: bash
        run: |
          curl -o wiremock.jar https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.9.1/wiremock-standalone-3.9.1.jar
      - name: Prepare and run integration tests
        id: integration-tests
        shell: bash
        run: |
          nohup java -jar wiremock.jar --port 9091 &
          nohup npm run start-feature &
          sleep 5
          npm run int-test
        # continue-on-error: true
        # replacing the above with if: always()
      - name: upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm_integration_test_artifacts
          path: |
            integration_tests/videos/
            integration_tests/screenshots/
            coverage/
            test_results/
            ctrf/
      - name: fail the action if the tests failed
        if: ${{ steps.integration-tests.outcome == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Integration tests failed')
    
      - name: Stop Redis server (optional)
        run: sudo service redis-server stop

